### ISSUE TITLE
建议支持更换内核，比如clash meta内核，以支持vless链接

### ISSUE THREAD

**Issue by xuconnery** [daodao97/EasyClash#1]

**Comment by daodao97** [comment]
目前使用的内核是Clash Premium，
Meta 包含 proxy/rule Provider 等功能吗，优势是哪些，没找到相关文档。

**Comment by xuconnery** [comment]
> 

https://github.com/MetaCubeX/Clash.Meta/releases

优势不清楚，因为我想让clash支持vless链接，搜了下，好像只有clash meta内核支持

**Comment by xuconnery** [comment]
目前Mac上支持vless的只有一个停更的qv2ray，再就是不甚完善的V2RayXS

**Comment by daodao97** [comment]
[v1.2](https://github.com/daodao97/EasyClash/releases) 支持 Clash.Meta 了
