### ISSUE TITLE
现在没有支持windows吗？

### ISSUE THREAD

**Issue by Circleee** [daodao97/EasyClash#2]

**Comment by daodao97** [comment]
I don't have a Windows device, so I can't debug it for now.

**Comment by daodao97** [comment]
v1.2 supported.

https://github.com/daodao97/EasyClash/releases/tag/v1.2

**Comment by Circleee** [comment]
ok  ， thank you

**Comment by lichaoyangnice** [comment]
@Circleee 还有安装包么？
