### ISSUE TITLE
An Error that pnpm can't find package @okiss/vform

### ISSUE THREAD

**Issue by angryLid** [daodao97/EasyClash#3]
When I run `pnpm install`, the following is printed:

> WARN  GET https://registry.npmmirror.com/@okiss/utils/-/@okiss/utils-0.0.8.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
 > WARN  GET https://registry.npmmirror.com/@okiss/vform/-/@okiss/vform-0.0.41.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.

then I detele the `pnpm-lock.yaml` run `pnpm install` again, it tells me :
>  ERR_PNPM_FETCH_404  GET https://registry.npmmirror.com/@okiss%2Fvform: Not Found - 404
> @okiss/vform is not in the npm registry, or you have no permission to fetch it.    

then I search "@okiss/vform" in [npm](https://www.npmjs.com/) and find no result .

It seems you're the author, so please publish it, thx.

**Comment by daodao97** [comment]
Please pull the repo in local, now use `@okiss/lib`.
